name: squrrl
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - loguru
  - pip
  - pre-commit
  - pytorch    
  - pytorch-cuda=12.1
  - torchaudio
  - torchvision
  - sentence-transformers
  - toml
  - typer
  - pip:
    - fasttext-langdetect
    - pymilvus==2.3.4
